<a href="https://colab.research.google.com/github/yoloaryan/Movie_recommendation_system/blob/main/Movie_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df= pd.read_csv("/content/movies_metadata.csv")

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16862 entries, 0 to 16861
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  16862 non-null  bool
 1   belongs_to_collection  2109 non-null   object
 2   budget                 16862 non-null  int64
 3   genres                 16862 non-null  object
 4   homepage               2241 non-null   object
 5   id                     16862 non-null  int64
 6   imdb_id                16859 non-null  object
 7   original_language      16862 non-null  object
 8   original_title         16862 non-null  object
 9   overview               16783 non-null  object
 10  popularity             16862 non-null  float64
 11  poster_path            16810 non-null  object
 12  production_companies   16861 non-null  object
 13  production_countries   16861 non-null  object
 14  release_date           16853 non-null  object
 15  revenue                16861 non-null  float64
 16  runtime                16846 non-null  float64
 17  spoken_languages       16861 non-null  object
 18  status                 16848 non-null  object
 19  tagline                10383 non-null  object
 20  title                  16861 non-null  object
 21  video                  16861 non-null  object
 22  vote_average           16861 non-null  float64
 23  vote_count             16861 non-null  float64
dtypes: bool(1), float64(5), int64(2), object(16)
memory usage: 3.0+ MB

In [ ]:
df.shape

(16862, 24)

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    14753
budget                       0
genres                       0
homepage                 14621
id                           0
imdb_id                      3
original_language            0
original_title               0
overview                    79
popularity                   0
poster_path                 52
production_companies         1
production_countries         1
release_date                 9
revenue                      1
runtime                     16
spoken_languages             1
status                      14
tagline                   6479
title                        1
video                        1
vote_average                 1
vote_count                   1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(5)

In [ ]:
#Remove duplicate rows
df= df.drop_duplicates().reset_index(drop= True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [ ]:
df.isnull().sum()

title              1
overview          79
genres             0
tagline         6478
vote_average       1
popularity         0
dtype: int64

In [ ]:
df= df.dropna(subset=['title'])

In [ ]:
df['overview']= df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
import ast
df['geners'] = df['genres'].apply(lambda x:" ".join([i['name']for i in ast.literal_eval(x)]))

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,geners
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943,Animation Comedy Family
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539,Adventure Fantasy Family
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,Romance Comedy
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495,Comedy Drama Romance
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519,Comedy

In [ ]:
df['tagline']= df['tagline'].fillna('')

In [ ]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
geners          0
dtype: int64

In [ ]:
df['tags'] = df['overview']+ " "+ df['genres']+" "+df['tagline']

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,geners,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",,7.7,21.946943,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,Romance Comedy,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519,Comedy,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}] Roll the dice and unleash the excitement!"

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  #lowercase
  text = text.lower()
  #remove the puncutation
  text = re.sub(r'[^a-zA-Z\s]','',text)

  words = text.split()
  words =[word for word in words if word not in stop_words]

  #lemmatize
  words =[lemmatizer.lemmatize(word) for word in words]


  return " ".join(words)

In [ ]:
df['tags']= df['tags'].apply(preprocess_text)

In [ ]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature id name adventure id name fantasy id name family roll dice unleash excitement'

In [ ]:
#covert into vectors

In [ ]:
#reseting the index

df = df.reset_index(drop = True)

In [ ]:
# wanting of the indices
indices =pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Toy Story                                   0
Jumanji                                     1
Grumpier Old Men                            2
Waiting to Exhale                           3
Father of the Bride Part II                 4
                                        ...
The New Daughter                        16851
Black Bread                             16852
Alibi                                   16853
Winnie the Pooh and a Day for Eeyore    16854
The Good Shepherd                       16855
Length: 16856, dtype: int64

In [ ]:
#apply vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf =TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix.shape

(16856, 50000)

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 681947 stored elements and shape (16856, 50000)>

In [ ]:
#import cosine similarity

from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title,n =10):
  if title not in indices:
    return['Movie not found']

  idx=indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1: n+1]

  # Ensure indices are within bounds before passing to iloc
  valid_indices = similar_idx[(similar_idx >= 0) & (similar_idx < len(df))]

  return df['title'].iloc[valid_indices]

In [ ]:
recommend('Betrayal')

8739                  Emmanuelle II
16391                  Early Spring
4304            Written on the Wind
13448                  The Big Lift
8478                 Clash by Night
1472         The Designated Mourner
1035          The Woman in Question
13198                          Love
8085     We Don't Live Here Anymore
12412                 Vantage Point
Name: title, dtype: object

In [ ]:
recommend('Black Bread')

2012          Children of the Corn
5133                 No Such Thing
4489               Little Monsters
2533           Son of Frankenstein
10631           House of Strangers
4008             The Monster Squad
7433     A Time for Drunken Horses
7428                    The Unsaid
4780                   Jabberwocky
10868           Youth of the Beast
Name: title, dtype: object

In [ ]:
recommend('Black Bread',3)

2012    Children of the Corn
5133           No Such Thing
4489         Little Monsters
Name: title, dtype: object

In [ ]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))